### ISSUE TITLE
Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by ikki-ai** [AndrejGajdos/link-preview-generator#9]
Hello 
i try to use your package but i got this error :
"Evaluation failed: TypeError: Cannot read property 'innerHTML' of null\n at __puppeteer_evaluation_script__:14:44" when trying this url:
https://www.laprovence.com/article/om/6063890/om-leonardo-balerdi-a-tire-daile.html

thanks for your help

**Comment by ikki-ai** [comment]
i got this one two:
2020-07-31T17:32:09.185614301Z Error: Failed to launch the browser process!
2020-07-31T17:32:09.185654313Z [0731/173209.181653:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
2020-07-31T17:32:09.185660676Z 
2020-07-31T17:32:09.185665452Z 
2020-07-31T17:32:09.185669398Z TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
2020-07-31T17:32:09.185673722Z 
2020-07-31T17:32:09.185677430Z at onClose (/usr/src/scrapper/node_modules/puppeteer/lib/Launcher.js:750:14)
2020-07-31T17:32:09.185681672Z at Interface.<anonymous> (/usr/src/scrapper/node_modules/puppeteer/lib/Launcher.js:739:50)
2020-07-31T17:32:09.185686484Z at Interface.emit (events.js:215:7)
2020-07-31T17:32:09.185708863Z at Interface.close (readline.js:403:8)
2020-07-31T17:32:09.185713748Z at Socket.onend (readline.js:180:10)
2020-07-31T17:32:09.185718212Z at Socket.emit (events.js:215:7)
2020-07-31T17:32:09.185722313Z at endReadableNT (_stream_readable.js:1184:12)
2020-07-31T17:32:09.185726749Z at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by baladin** [comment]
Error: Evaluation failed: TypeError: Cannot read property 'innerHTML' of null
    at <anonymous>:14:44
    at ExecutionContext._evaluateInternal (/home/ec2-user/clouthub-backend-5.0/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/ec2-user/clouthub-backend-5.0/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async getTitle (/home/ec2-user/clouthub-backend-5.0/node_modules/link-preview-generator/index.js:77:17)
    at async module.exports (/home/ec2-user/clouthub-backend-5.0/node_modules/link-preview-generator/index.js:173:15)

**Comment by AndrejGajdos** [comment]
@frederic117 @baladin fixed [here](https://github.com/AndrejGajdos/link-preview-generator/commit/0c3fc45f555beec864a62ef7e7e4965d0e998e76)
